#!/bin/bash
DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`

echo -e "$SCRIPT: BEGIN `date`"

if [ ! -e 'package.json' ]; then
  echo -e "$SCRIPT: package.json not found in current folder (ERROR)"
  exit 911
fi

echo -e "${SCRIPT}: updating Vuetify..."
npm install --save \
  vue@latest \
  vite@latest \
  @vitejs/plugin-vue@latest \
  vuetify@latest \
  vite-plugin-vuetify@latest \
  # END NPM INSTALL

echo -e "$SCRIPT: END `date`"
