export const DEBUG_ADD_CARD = 0;
export const DEBUG_AUDIO    = 0;
export const DEBUG_CLICK    = 0;
export const DEBUG_FOCUS    = 0;
export const DEBUG_GDPR     = 0;
export const DEBUG_HOME     = true;
export const DEBUG_KEY      = 0;
export const DEBUG_LEGACY   = 0;
export const DEBUG_LOAD     = 0;
export const DEBUG_LOG_HTML = 0; // when debug console doesn't work
export const DEBUG_MOUNTED  = 0;
export const DEBUG_OPEN_CARD= true;
export const DEBUG_ROUTE    = true;
export const DEBUG_SCROLL   = 0;
export const DEBUG_SEARCH   = 0;
export const DEBUG_SETTINGS = 0;
export const DEBUG_STARTUP  = 0;
export const DEBUG_SUTTA    = 0;
export const DEBUG_TUTORIAL = 0;
export const DEBUG_UPDATED  = 0;
export const DEBUG_VISIBLE  = 0;  // card.isVisible scrolling
export const DEBUG_WAITING  = 0;
export const DEBUG_WIKI     = true;
