export const DBG_ADD_CARD = 0;
export const DBG_AUDIO    = 0;
export const DBG_BLUR     = 0;
export const DBG_CLICK    = 0;
export const DBG_COPY     = 0;
export const DBG_FOCUS    = 0;
export const DBG_GDPR     = 0;
export const DBG_HOME     = 0;
export const DBG_KEY      = 0;
export const DBG_LEGACY   = 0;
export const DBG_LOAD     = 0;
export const DBG_LOG_HTML = 0; // when debug console doesn't work
export const DBG_TBD      = 0; // experimental feature
export const DBG_MOUNTED  = 0;
export const DBG_OPEN_CARD= 0;
export const DBG_PATH_TO_CARD = 0;
export const DBG_ROUTE    = 0;
export const DBG_SCROLL   = 0;
export const DBG_SEARCH   = 0;
export const DBG_SETTINGS = 0;
export const DBG_STARTUP  = 0;
export const DBG_SUTTA    = 0;
export const DBG_TUTORIAL = 0;
export const DBG_UPDATED  = 0;
export const DBG_VERBOSE  = 0;  // trace non-mutative logic
export const DBG_VIEWPORT = 0;
export const DBG_VISIBLE  = 0;  // card.isVisible scrolling
export const DBG_WAITING  = 0;
export const DBG_WIKI     = 0;

export const APP_BAR_H    = 40;
