export const DBG_ADD_CARD = 0;
export const DBG_AUDIO    = 0;
export const DBG_CLICK    = true;
export const DBG_FOCUS    = true;
export const DBG_GDPR     = 0;
export const DBG_HOME     = 0;
export const DBG_KEY      = 0;
export const DBG_LEGACY   = 0;
export const DBG_LOAD     = 0;
export const DBG_LOG_HTML = 0; // when debug console doesn't work
export const DBG_MOUNTED  = 0;
export const DBG_OPEN_CARD= 0;
export const DBG_PATH_TO_CARD = 0;
export const DBG_ROUTE    = 0;
export const DBG_SCROLL   = true;
export const DBG_SEARCH   = 0;
export const DBG_SETTINGS = 0;
export const DBG_STARTUP  = 0;
export const DBG_SUTTA    = 0;
export const DBG_TUTORIAL = 0;
export const DBG_UPDATED  = 0;
export const DBG_VISIBLE  = 0;  // card.isVisible scrolling
export const DBG_WAITING  = 0;
export const DBG_WIKI     = 0;
